{% set version = "1.2.0" %}

package:
  name: r-blob
  version: {{ version }}

source:
  fn: blob_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/blob_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/blob/blob_{{ version }}.tar.gz
  sha256: 1af1cfa28607bc0e2f1f01598a00a7d5d1385ef160a9e79e568f30f56538e023

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-prettyunits
    - r-rlang
    - r-vctrs

  run:
    - r-base
    - r-prettyunits
    - r-rlang
    - r-vctrs

test:
  commands:
    - $R -e "library('blob')"  # [not win]
    - "\"%R%\" -e \"library('blob')\""  # [win]

about:
  home: https://github.com/hadley/blob
  license: GPL-3
  summary: R's raw vector is useful for storing a single binary object. What if you want to put
    a vector of them in a data frame? The blob package provides the blob object, a list
    of raw vectors, suitable for use as a column in data frame.
  license_family: GPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - bgruening
    - daler
    - johanneskoester
    - rvalieris
