{% set version = "1.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-blob
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/blob_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/blob/blob_{{ version }}.tar.gz
  sha256: 2d88d683ee3d1b56b332b5c7769979b5d3994b5d9285ea634ec919576da3631b

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rlang
    - r-vctrs >=0.2.1
  run:
    - r-base
    - r-rlang
    - r-vctrs >=0.2.1

test:
  commands:
    - $R -e "library('blob')"           # [not win]
    - "\"%R%\" -e \"library('blob')\""  # [win]

about:
  home: https://github.com/tidyverse/blob
  license: GPL-3.0-only
  summary: R's raw vector is useful for storing a single binary object.  What if you want to put a vector of them in a data frame? The 'blob' package provides the blob object, a list of raw vectors, suitable for use as a column in data frame.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris

# Package: blob
# Title: A Simple S3 Class for Representing Vectors of Binary Data ('BLOBS')
# Version: 1.2.1
# Authors@R: c(person(given = "Hadley", family = "Wickham", role = "aut"), person(given = "Kirill", family = "Muller", role = "cre", email = "krlmlr+r@mailbox.org"), person(given = "RStudio", role = "cph"))
# Description: R's raw vector is useful for storing a single binary object.  What if you want to put a vector of them in a data frame? The 'blob' package provides the blob object, a list of raw vectors, suitable for use as a column in data frame.
# License: GPL-3
# URL: https://github.com/tidyverse/blob
# BugReports: https://github.com/tidyverse/blob/issues
# Imports: methods, rlang, vctrs (>= 0.2.1)
# Suggests: covr, crayon, pillar (>= 1.2.1), testthat
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-01-20 22:32:38 UTC; kirill
# Author: Hadley Wickham [aut], Kirill Muller [cre], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2020-01-20 22:50:02 UTC
