{% set version = "1.1.1" %}

package:
  name: r-blob
  version: {{ version }}

source:
  fn: blob_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/blob_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/blob/blob_{{ version }}.tar.gz
  sha256: accbf9c9746c983e4108c8709995e54e61611ea7e2c51d4b6a0d813261484f53

build:
  noarch: generic
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-prettyunits

  run:
    - r-base
    - r-prettyunits

test:
  commands:
    - $R -e "library('blob')"  # [not win]
    - "\"%R%\" -e \"library('blob')\""  # [win]

about:
  home: https://github.com/hadley/blob
  license: GPL-3
  summary: R's raw vector is useful for storing a single binary object. What if you want to put
    a vector of them in a data frame? The blob package provides the blob object, a list
    of raw vectors, suitable for use as a column in data frame.
  license_family: GPL

extra:
  recipe-maintainers:
    - dpryan79
    - bgruening
    - daler
    - johanneskoester
    - rvalieris
