travis:
  secure:
    BINSTAR_TOKEN: e7cq8CaNiv2D9f8KXP9+7QIcCfM+KU6mkbG8yma2iuRQlJUx+ODK72ThnWWIn3ijD4cITZb4GbwSi4IyIeo38A2CRsO+cTr1N1udZZt3aZgx10uH28AbM74pZmPv7uw0Ifxj3iU2bdBclIJG/vKwL4H89CnAqBCLscJ+jcjbhNlraB/9gDXOxaytk3pJemnhmAEuGJKGECezxbc1NLtiZ1z2rOykKwwqIKuBaXwVQsVIy6PyT1NeWbHqH/+YevOX4gfbLzvzhio41M3qiv5mosUc4PxFP+luTJzajbxDJvx93hPKXaSEOb10POrIEFddinNXIFa6WCTVQCg4IKQ3WlLJoEIx1q+gZVxuwSuCQnNp4UtNfn+NnLIq6twgvscBZ17nV78et5q0xdrD41Lq5U0ZJMoKRcrnB3S0wGjaUu6tNPGWwqj5dCn10sj7khmXftYsBWhPk43wiBTJEnmVfHxHZIMyoyitvTR51XaPAl44XuoiBT8NPtBHSA9qnR7fGiDiUGBWrHDlMcmYMHVc5hXCM2XZrrGc5PZLuS/wUj+RNWw8bgRSGZ8wrnuPYR378aMgI6EGUP+9C+5MlV1MSMPU2BEZqljM9AMcdvSxhV7Eax1JYhSrwQ8pT/2PYCwQujmwCrHjM3u2KSSmnD0o5P5I3SNqg2qcAJDgvwgL0wc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
