appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: mGkx/wFBSqxr0+Ov35zeNM7xItkhASzPLZttydWQueblBANvzKTlX8jqsoQR9DrOVgBzhXuKTdrVg30VwI4x2XDI2gR5PhKVDxfd/U97NMZ/FVfjTb/pBgafDF2flt2Of6zxgXIaZy3J/zW9VCquqj2y4McFuEFVyQ7Zphuftap4COx3S3qRhdm0UB25huIbv2hrUFuMjHWXaWqgKGA56WSNGFf/I8QzYSxEigEEUUAHeZYsBphzPVg4gigf98KZS98zrTzEYFTNv2kkX2QuRy83fqXWqWERtPSRxqpTI/NLYlpNpBuyffcIqCvUHPqGuYtt1P3Ss9mIyMclceIoexqX+EMxTyck1f5CgmGcvRcauDj7Cm0dgbmiFok3sItPosQaAy2jCCQGcGIM0u4Pubmqa3X8zoMcqeLxrVVl3yZY+NxKOgo5jAyS7dBPDrq5vAAKf6ECxWMvahYHKBE2bK0El7A+fXaklZjeYjDydAZ8oLmyYqDY5Wu2eCa74Sx+aNboXDpjRdEOjWIG/vOaUd0F0JxWHYkm5tLw+NIeDCdPQqeh/3SMoqG5UkYbVpkWUQbs1b63galQHYrs/Zj3yWCVoaNcA5HTXGshRI25k3CTBsput2pP076cjWzM4SKavp7G3jm77iCBlHL+MuMMHwAYz/1ENJF0yimKraFizbg=
conda_forge_output_validation: true
